name: Deploy to Server
 
on:
  push:
    branches:
      - main  # Change to your branch name if needed
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no user@your-server-ip "
          cd /var/www/project && git pull && sudo systemctl restart your-service
        "
