name: Deploy to Server on Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        mkdir -p ~/.ssh
        ssh-keyscan -H 103.251.19.235 >> ~/.ssh/known_hosts
        ssh -i private_key user@103.251.19.235 << 'EOF'
          cd /var/www/project
          git pull
          sudo systemctl restart your-service
        EOF

    - name: Cleanup SSH Key
      shell: bash
      run: |
        rm -f private_key
